LOCK TABLES `item_project` WRITE;
SET SESSION FOREIGN_KEY_CHECKS=0;
/*!40000 ALTER TABLE `item_project` DISABLE KEYS */;
INSERT INTO `item_project` VALUES
(1,'MPEX',NULL);
/*!40000 ALTER TABLE `item_project` ENABLE KEYS */;
UNLOCK TABLES;
