#!/bin/sh

# Called from ~/.bashrc via "source ~/cdb-support/env/cdb-env", sets up environment environment variables for customization etc.

source ~/cdb-deployment/custom/env/cdb-env-passwd
source ~/cdb-deployment/custom/env/cdb-env-vars

export DIR_BIN=~/cdb-support/bin
alias bin="cd $DIR_BIN"
export PATH=$PATH:$DIR_BIN

export DIR_CDB_CURRENT=/opt/cdb/current
alias cdb="cd $DIR_CDB_CURRENT"

